# Generated by Django 3.0.3 on 2020-04-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_resumes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resume',
            new_name='resume_file',
        ),
    ]
